import React from 'react'

export default function Index() {
  return (
    <>
      <h2>PCS Real Estate</h2> <p>was founded in 2024 by PCS Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione quia sint a, dolores iusto modi! Architecto pariatur accusamus qui atque dolorum laborum quidem molestias eum iste voluptates necessitatibus neque quasi eligendi illo, sed perspiciatis voluptatibus modi optio quos, enim libero, eius doloribus iure. Deserunt consectetur ipsa ea aperiam aspernatur laudantium possimus sint. Maiores animi, explicabo tempore, voluptas voluptatem impedit molestias ex exercitationem magnam dolorem possimus culpa quaerat assumenda tempora sequi. Inventore neque fugit harum eaque quasi, at veritatis velit perferendis, eum veniam culpa nesciunt ratione corrupti atque doloremque voluptas natus itaque, ipsa fuga? Voluptatem vero exercitationem, reiciendis quia beatae aspernatur. Ea ducimus qui repellendus deleniti ab quis enim eaque error est doloremque sunt rem laudantium, quae inventore sint asperiores natus ex modi recusandae mollitia cum quibusdam voluptatibus quia. Dolorem, nobis in repudiandae eaque maiores numquam adipisci distinctio voluptatum architecto fugit accusamus, qui tenetur repellendus veniam vitae, nisi cumque minima officiis consequuntur odit asperiores! Fuga nemo dolor rerum explicabo voluptatum! Sit nulla aspernatur eius veritatis earum! Nihil eum libero, iure minus perspiciatis voluptates beatae ipsum quibusdam dolorem enim perferendis, sapiente, eius quos fugit cumque laboriosam labore! Corrupti voluptatum atque est cupiditate labore! Repudiandae voluptates at eveniet nostrum eius voluptatem voluptate dolorum illum laudantium obcaecati ducimus suscipit, quae magni ad reiciendis non consequuntur vero tempore unde nulla quibusdam omnis? Sint expedita et debitis tenetur ex hic blanditiis repellat officia maiores molestiae excepturi deleniti quisquam porro iusto a eos architecto doloremque, eum magnam, at sed non! Ducimus molestiae tempora, praesentium neque nostrum numquam.</p>
    </>
  )
}
